FROM centos:centos7
MAINTAINER Zenoss, Inc <dev@zenoss.com> 

RUN yum -y update; yum clean all

# build ssh dependencies
RUN yum -y install openssh-server openssh-clients

RUN mkdir -p /var/run/sshd ; chmod -rx /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
RUN su - root -c "mkdir -p ~/.ssh && ssh-keygen -f ~/.ssh/id_rsa -t rsa -N '' && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && echo StrictHostKeyChecking no >> /etc/ssh/ssh_config"
CMD ["/usr/sbin/sshd", "-D"]

# build ceph dependencies
RUN yum install -y ntp ntpdate ntp-doc curl wget screen tmux sudo
RUN [ -f /etc/selinux/config ] && sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config || true
RUN which setenforce && setenforce 0 || true


ADD ceph.repo /etc/yum.repos.d/ceph.repo
RUN yum update && yum install -y ceph-deploy
RUN yum install -y yum-plugin-priorities

ENV CEPH_USER ceph
RUN useradd -d /home/$CEPH_USER -m $CEPH_USER
RUN echo "$CEPH_USER ALL = (root) NOPASSWD:ALL" > /etc/sudoers.d/$CEPH_USER
RUN chmod 0440 /etc/sudoers.d/$CEPH_USER

RUN su - $CEPH_USER -c "mkdir -p ~/.ssh && ssh-keygen -f ~/.ssh/id_rsa -t rsa -N '' && cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"

ADD quick-ceph-cluster.sh /quick-ceph-cluster.sh
ADD setup-hosts.sh /setup-hosts.sh

